# Generated by Django 4.2 on 2023-04-16 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entraineur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('non', models.CharField(max_length=50)),
                ('non_entraineur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualisation.entraineur')),
            ],
        ),
        migrations.CreateModel(
            name='Tournoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('non', models.CharField(max_length=50)),
                ('non_lieu', models.CharField(max_length=50, null=True)),
                ('data_debut', models.DateField(null=True)),
                ('data_fin', models.DateField(null=True)),
                ('nombre_de_poules', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Poule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_poule', models.IntegerField()),
                ('liste_equipe', models.ManyToManyField(to='visualisation.equipe')),
                ('tournoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualisation.tournoi')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('lieu', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('equipe1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas1', to='visualisation.equipe')),
                ('equipe2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas2', to='visualisation.equipe')),
                ('poule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualisation.poule')),
            ],
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('non', models.CharField(max_length=20)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualisation.equipe')),
            ],
        ),
    ]
