# Generated by Django 4.2 on 2023-04-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournoi',
            name='liste_equipes',
            field=models.ManyToManyField(null=True, to='visualisation.equipe'),
        ),
    ]
