# Generated by Django 4.2 on 2023-04-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='non_entraineur',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Entraineur',
        ),
    ]
