# Generated by Django 4.2 on 2023-04-17 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0003_tournoi_liste_equipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poule',
            name='liste_equipe',
        ),
    ]
