# Generated by Django 4.2 on 2023-04-20 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='object_id',
        ),
    ]
